# Generated by Django 4.1.7 on 2024-09-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status_codes', '0001_initial'),
        ('poets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyric', models.TextField(max_length=256, verbose_name='سروده')),
                ('state', models.SmallIntegerField(choices=[(0, 'submitted'), (1, 'approved'), (2, 'applied'), (-1, 'disapproved')], default=0, help_text='وضعیت فعلی این سروده پیشنهادی را توصیف می\u200cکند')),
                ('poet', models.ForeignKey(help_text='سراینده این سروده پیشنهادی', on_delete=django.db.models.deletion.CASCADE, to='poets.poet', verbose_name='سراینده')),
                ('status_code', models.ForeignKey(help_text='کد وضعیتی که این سروده پیشنهادی قرار است آن را توصیف می\u200cکند', on_delete=django.db.models.deletion.CASCADE, to='status_codes.statuscode', verbose_name='کد وضعیت')),
            ],
            options={
                'verbose_name': 'بیت سروده پیشنهادی',
                'verbose_name_plural': 'ابیات پیشنهادی',
                'ordering': ['-id'],
            },
        ),
    ]
