# Generated by Django 4.1.7 on 2023-03-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("pseudonym", models.CharField(max_length=100, verbose_name="تخلص")),
                (
                    "biography",
                    models.TextField(max_length=1024, verbose_name="زندگینامه"),
                ),
                (
                    "ganjoor_link",
                    models.URLField(
                        help_text="پیوند نمایه شاعر در وبسایت گنجور",
                        verbose_name="پیوند گنچور",
                    ),
                ),
            ],
            options={
                "verbose_name": "شعر",
                "verbose_name_plural": "شعرا",
            },
        ),
        migrations.CreateModel(
            name="StatusCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(verbose_name="کد وضعیت")),
                ("description", models.TextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "کد وضعیت",
                "verbose_name_plural": "کد\u200cهای وضعیت",
            },
        ),
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lyric", models.CharField(max_length=255, verbose_name="بیت شعر")),
                (
                    "ganjoor_link",
                    models.URLField(
                        help_text="پیوتد قطعه کامل بیت شعر در وبسایت گنجور",
                        verbose_name="پیوند گنچور",
                    ),
                ),
                (
                    "poet",
                    models.ForeignKey(
                        help_text="نام سراینده این بیت شعر",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poems.poet",
                        verbose_name="شاعر",
                    ),
                ),
                (
                    "status_code",
                    models.ForeignKey(
                        help_text="کد وضعیتی که این بیت شعر آن را توصیف می\u200cکند",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poems.statuscode",
                        verbose_name="کد وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشعار",
            },
        ),
    ]
