# Generated by Django 4.1.7 on 2023-03-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("pseudonym", models.CharField(max_length=100, verbose_name="تخلص")),
                (
                    "biography",
                    models.TextField(max_length=1024, verbose_name="زندگینامه"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        help_text="چهرک سراینده", upload_to="", verbose_name="آواتار"
                    ),
                ),
                (
                    "ganjoor_link",
                    models.URLField(
                        help_text="پیوند نمایه سراینده در وبسایت گنجور",
                        verbose_name="پیوند گنچور",
                    ),
                ),
            ],
            options={
                "verbose_name": "سراینده",
                "verbose_name_plural": "سرایندگان",
            },
        ),
        migrations.CreateModel(
            name="StatusCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(verbose_name="کد وضعیت")),
                (
                    "title",
                    models.CharField(max_length=32, null=True, verbose_name="عنوان"),
                ),
                (
                    "group",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Informational"),
                            (2, "Successful"),
                            (3, "Redirection"),
                            (4, "Client Error"),
                            (5, "Server Error"),
                        ],
                        verbose_name="گروه پاسخ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "mdn_link",
                    models.URLField(
                        blank=True,
                        help_text="پیوند کد وضعیت مربوطه در وبسایت mdn",
                        null=True,
                        verbose_name="پیوند mdn",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد وضعیت",
                "verbose_name_plural": "کد\u200cهای وضعیت",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lyric", models.CharField(max_length=255, verbose_name="بیت سروده")),
                (
                    "ganjoor_link",
                    models.URLField(
                        help_text="پیوتد قطعه کامل سروده در وبسایت گنجور",
                        verbose_name="پیوند گنچور",
                    ),
                ),
                (
                    "poet",
                    models.ForeignKey(
                        help_text="نام سراینده این بیت سروده",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poems.poet",
                        verbose_name="سراینده",
                    ),
                ),
                (
                    "status_code",
                    models.ForeignKey(
                        help_text="کد وضعیتی که این بیت سروده آن را توصیف می\u200cکند",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poems.statuscode",
                        verbose_name="کد وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "بیت سروده",
                "verbose_name_plural": "ابیات",
            },
        ),
    ]
